* minor: more pronounced script error messages

diff --git a/host/tarball/share/myx.common/bin/lib/installUser b/host/tarball/share/myx.common/bin/lib/installUser
--- a/host/tarball/share/myx.common/bin/lib/installUser
+++ b/host/tarball/share/myx.common/bin/lib/installUser
@@ -12,8 +12,8 @@ InstallUser(){
 	local NAME="$1" TITLE="$2" 
 	local UGID="$3" UHOME="${4:-/home/$NAME/}"
 	
-	[ -z "$NAME" ] && echo "InstallUser: username is required!" && exit 1
-	[ -z "$TITLE" ] && echo "InstallUser: usertitle is taken from name ($NAME)!" && TITLE="$NAME"
+	[ -z "$NAME" ] && echo "ERROR: InstallUser: username is required!" >&2 && exit 1
+	[ -z "$TITLE" ] && echo "WARNING: InstallUser: usertitle is taken from name ($NAME)!" >&2 && TITLE="$NAME"
 
 	pwd_mkdb /etc/master.passwd
 
diff --git a/host/tarball/share/myx.common/bin/os/growSlashFsUfs b/host/tarball/share/myx.common/bin/os/growSlashFsUfs
--- a/host/tarball/share/myx.common/bin/os/growSlashFsUfs
+++ b/host/tarball/share/myx.common/bin/os/growSlashFsUfs
@@ -37,17 +37,17 @@ OsGrowSlashFsUfs(){
 			fi
 		done
 		
-		echo "Failed: can't detect device and partition (yet)" >&2
+		echo "ERROR: Failed: can't detect device and partition (yet)" >&2
 		return 1;
 	else
 		if [ "`geom disk status -s $DISK`" != "" ] ; then
 		else
-			echo "Failed: specified disk is invalid: $DISK" >&2
+			echo "ERROR: Failed: specified disk is invalid: $DISK" >&2
 			return 1;
 		fi
 		if [ "`gpart status -s $PART`" != "" ] && [ "`gpart show $PART | grep freebsd-ufs`" != "" ] ; then
 		else
-			echo "Failed: specified part is invalid (or does't contain UFS filesystem): $PART" >&2
+			echo "ERROR: Failed: specified part is invalid (or does't contain UFS filesystem): $PART" >&2
 			return 1;
 		fi
 	fi
@@ -64,7 +64,7 @@ OsGrowSlashFsUfs(){
 	echo "Grow: disk: $DISK, part: $PART, indx: $INDX, swap: $SWAP" >&2
 
 	if [ "$INDX" = "" ] ; then
-		echo "Failed: can't detect partition index (yet?)" >&2
+		echo "ERROR: Failed: can't detect partition index (yet?)" >&2
 		return 1;
 	fi
 	
diff --git a/host/tarball/share/myx.common/bin/vm/create b/host/tarball/share/myx.common/bin/vm/create
--- a/host/tarball/share/myx.common/bin/vm/create
+++ b/host/tarball/share/myx.common/bin/vm/create
@@ -10,7 +10,7 @@ VmCreate(){
     local VMHDD="$1"  ; shift
     	
     if [ -z "$VMTYPE" -o -z "$VMNAME" -o -z "$VMCPUS" -o -z "$VMRAM" -o -z "$VMHDD" ] ; then
-		echo "Syntax error: vm/create: check arguments." >&2
+		echo "ERROR: Syntax error: vm/create: check arguments." >&2
 		return 1
     fi
     
@@ -34,14 +34,14 @@ VmCreate(){
     	VMLAN1="$1" ; shift
     	VMMAC1="$1" ; shift
 	    if [ -z "$VMLAN1" -o -z "$VMMAC1" ] ; then
-			echo "Syntax error: vm/create: network #2: invalid arguments" >&2
+			echo "ERROR: Syntax error: vm/create: network #2: invalid arguments" >&2
 			return 1
 	    fi
     fi
     
     local VMISO="$1" ; shift
     if [ -z "$VMISO" ] ; then
-		echo "Syntax error: vm/create: iso image: invalid arguments" >&2
+		echo "ERROR: Syntax error: vm/create: iso image: invalid arguments" >&2
 		return 1
     fi
     	
@@ -72,7 +72,7 @@ VmCreate(){
 				;;
 				
 			*)
-				echo "Error: vm/create: Unknown vm type: $VMTYPE" >&2
+				echo "ERROR: vm/create: Unknown vm type: $VMTYPE" >&2
 			    return 1
 			    ;;
 				
