* icons in errors

diff --git a/host/tarball/share/myx.common/bin/lib/installUser b/host/tarball/share/myx.common/bin/lib/installUser
--- a/host/tarball/share/myx.common/bin/lib/installUser
+++ b/host/tarball/share/myx.common/bin/lib/installUser
@@ -12,7 +12,7 @@ InstallUser(){
 	local NAME="$1" TITLE="$2" 
 	local UGID="$3" UHOME="${4:-/home/$NAME}"
 	
-	[ -z "$NAME" ] && echo "ERROR: InstallUser: username is required!" >&2 && exit 1
+	[ -z "$NAME" ] && echo "⛔ ERROR: InstallUser: username is required!" >&2 && exit 1
 	[ -z "$TITLE" ] && echo "WARNING: InstallUser: usertitle is taken from name ($NAME)!" >&2 && TITLE="$NAME"
 
 	pwd_mkdb /etc/master.passwd
diff --git a/host/tarball/share/myx.common/bin/lib/installUserPasswordHash b/host/tarball/share/myx.common/bin/lib/installUserPasswordHash
--- a/host/tarball/share/myx.common/bin/lib/installUserPasswordHash
+++ b/host/tarball/share/myx.common/bin/lib/installUserPasswordHash
@@ -11,8 +11,8 @@ InstallUserPasswordHash(){
 
 	local NAME="$1" HASH="$2" 
 	
-	[ -z "$NAME" ] && echo "ERROR: InstallUserPasswordHash: username is required!" >&2 && exit 1
-	[ -z "$HASH" ] && echo "ERROR: InstallUserPasswordHash: password hash is required!" >&2 && exit 1
+	[ -z "$NAME" ] && echo "⛔ ERROR: InstallUserPasswordHash: username is required!" >&2 && exit 1
+	[ -z "$HASH" ] && echo "⛔ ERROR: InstallUserPasswordHash: password hash is required!" >&2 && exit 1
 
 	pwd_mkdb /etc/master.passwd
 	echo "$HASH" | /usr/sbin/pw usermod "$NAME" -H 0
diff --git a/host/tarball/share/myx.common/bin/os/growSlashFsUfs b/host/tarball/share/myx.common/bin/os/growSlashFsUfs
--- a/host/tarball/share/myx.common/bin/os/growSlashFsUfs
+++ b/host/tarball/share/myx.common/bin/os/growSlashFsUfs
@@ -34,17 +34,17 @@ OsGrowSlashFsUfs(){
 			fi
 		done
 		
-		echo "ERROR: Failed: can't detect device and partition (yet)" >&2
+		echo "⛔ ERROR: Failed: can't detect device and partition (yet)" >&2
 		return 1;
 	fi
 
 	if [ "`geom disk status -s $DISK`" = "" ] ; then
-		echo "ERROR: Failed: specified disk is invalid: $DISK" >&2
+		echo "⛔ ERROR: Failed: specified disk is invalid: $DISK" >&2
 		return 1;
 	fi
 
 	if [ "`gpart status -s $PART`" = "" ] || [ "`gpart show $PART | grep freebsd-ufs`" = "" ] ; then
-		echo "ERROR: Failed: specified part is invalid (or does't contain UFS filesystem): $PART" >&2
+		echo "⛔ ERROR: Failed: specified part is invalid (or does't contain UFS filesystem): $PART" >&2
 		return 1;
 	fi
 	
@@ -60,7 +60,7 @@ OsGrowSlashFsUfs(){
 	echo "Grow: disk: $DISK, part: $PART, indx: $INDX, swap: $SWAP" >&2
 
 	if [ "$INDX" = "" ] ; then
-		echo "ERROR: Failed: can't detect partition index (yet?)" >&2
+		echo "⛔ ERROR: Failed: can't detect partition index (yet?)" >&2
 		return 1;
 	fi
 	
diff --git a/host/tarball/share/myx.common/bin/setup/bhyve b/host/tarball/share/myx.common/bin/setup/bhyve
--- a/host/tarball/share/myx.common/bin/setup/bhyve
+++ b/host/tarball/share/myx.common/bin/setup/bhyve
@@ -14,7 +14,7 @@ type ReplaceLine >/dev/null 2>&1 || \
 SetupBhyve(){
 
 	if [ "`zfs list| grep -ic -e /`" -eq 0 ]; then
-		echo "ERROR: setup/bhyve: ZFS file-system required!" >&2
+		echo "⛔ ERROR: setup/bhyve: ZFS file-system required!" >&2
 	    return 1
 	fi
 	
diff --git a/host/tarball/share/myx.common/bin/vm/create b/host/tarball/share/myx.common/bin/vm/create
--- a/host/tarball/share/myx.common/bin/vm/create
+++ b/host/tarball/share/myx.common/bin/vm/create
@@ -10,14 +10,14 @@ VmCreate(){
     local VMHDD="$1"  ; shift
     	
     if [ -z "$VMTYPE" -o -z "$VMNAME" -o -z "$VMCPUS" -o -z "$VMRAM" -o -z "$VMHDD" ] ; then
-		echo "ERROR: Syntax error: vm/create: check arguments." >&2
+		echo "⛔ ERROR: Syntax error: vm/create: check arguments." >&2
 		return 1
     fi
     
 	local VMHDD="`echo "$VMHDD" | sed 's/[ ]*//g;s/[bB]$//;s/^.*[^0-9gkmt].*$//i;s/t$/Xg/i;s/g$/Xm/i;s/m$/Xk/i;s/k$/X/i;s/X/*1024/g' | bc`"
 
 	if [ -z "$VMHDD" ] ; then
-		echo "ERROR: Syntax error: vm/create: check arguments: disk size is invalid!" >&2
+		echo "⛔ ERROR: Syntax error: vm/create: check arguments: disk size is invalid!" >&2
 		return 1
 	fi
 
@@ -42,7 +42,7 @@ VmCreate(){
     	VMLAN0="$1" ; shift
     	VMMAC0="$1" ; shift
 	    if [ -z "$VMLAN0" -o -z "$VMMAC0" ] ; then
-			echo "ERROR: Syntax error: vm/create: network #1: invalid arguments" >&2
+			echo "⛔ ERROR: Syntax error: vm/create: network #1: invalid arguments" >&2
 			return 1
 	    fi
     fi
@@ -52,7 +52,7 @@ VmCreate(){
     	VMLAN1="$1" ; shift
     	VMMAC1="$1" ; shift
 	    if [ -z "$VMLAN1" -o -z "$VMMAC1" ] ; then
-			echo "ERROR: Syntax error: vm/create: network #2: invalid arguments" >&2
+			echo "⛔ ERROR: Syntax error: vm/create: network #2: invalid arguments" >&2
 			return 1
 	    fi
     fi
@@ -62,7 +62,7 @@ VmCreate(){
     	VMLAN2="$1" ; shift
     	VMMAC2="$1" ; shift
 	    if [ -z "$VMLAN2" -o -z "$VMMAC2" ] ; then
-			echo "ERROR: Syntax error: vm/create: network #3: invalid arguments" >&2
+			echo "⛔ ERROR: Syntax error: vm/create: network #3: invalid arguments" >&2
 			return 1
 	    fi
     fi
@@ -72,19 +72,19 @@ VmCreate(){
     	VMLAN3="$1" ; shift
     	VMMAC3="$1" ; shift
 	    if [ -z "$VMLAN3" -o -z "$VMMAC3" ] ; then
-			echo "ERROR: Syntax error: vm/create: network #4: invalid arguments" >&2
+			echo "⛔ ERROR: Syntax error: vm/create: network #4: invalid arguments" >&2
 			return 1
 	    fi
     fi
 
     if [ "$1" == "--net" ] ; then
-		echo "ERROR: Only up to 4 network interfaces supported" >&2
+		echo "⛔ ERROR: Only up to 4 network interfaces supported" >&2
 		return 1
 	fi
 
     local VMISO="$1" ; shift
     if [ -z "$VMISO" ] ; then
-		echo "ERROR: Syntax error: vm/create: iso image: invalid arguments" >&2
+		echo "⛔ ERROR: Syntax error: vm/create: iso image: invalid arguments" >&2
 		return 1
     fi
     	
@@ -125,7 +125,7 @@ VmCreate(){
 				;;
 				
 			*)
-				echo "ERROR: vm/create: Unknown vm type: $VMTYPE" >&2
+				echo "⛔ ERROR: vm/create: Unknown vm type: $VMTYPE" >&2
 			    return 1
 			    ;;
 				
