* custom install java and other commands

diff --git a/host/tarball/share/myx.common/bin/lib/installAuthorizedKey b/host/tarball/share/myx.common/bin/lib/installAuthorizedKey
--- a/host/tarball/share/myx.common/bin/lib/installAuthorizedKey
+++ b/host/tarball/share/myx.common/bin/lib/installAuthorizedKey
@@ -8,6 +8,9 @@ InstallAutorizedKey(){
 	local NAME="$1" KEY="$2"
 	local HOME="/home/$NAME"
 	local KEYS="$HOME/.ssh/authorized_keys"
+
+	[ -z "$NAME" ] && echo "InstallAutorizedKey: username is required!" && exit 1
+	[ -z "$KEY" ] && echo "InstallAutorizedKey: key is required!" && exit 2
 	
 	mkdir -p "$HOME/.ssh"
 	touch "$KEYS"
@@ -18,11 +21,8 @@ InstallAutorizedKey(){
 	chmod 600 "$KEYS"
 }
 
-
-NAME="$1"
-KEY="$2"
-
-[ -z "$NAME" ] && echo "username is required!" && exit 1
-[ -z "$KEY" ] && echo "key is required!" && exit 2
-
-InstallAutorizedKey "$NAME" "$KEY"
+case "$0" in
+	*/myx.common/bin/lib/installAutorizedKey) 
+		InstallAuthorizedKey $@
+	;;
+esac
diff --git a/host/tarball/share/myx.common/bin/lib/installRootAuthorizedKey b/host/tarball/share/myx.common/bin/lib/installRootAuthorizedKey
--- a/host/tarball/share/myx.common/bin/lib/installRootAuthorizedKey
+++ b/host/tarball/share/myx.common/bin/lib/installRootAuthorizedKey
@@ -5,7 +5,12 @@ set -e
 . ${0%/*}/../../include/subr.sh
 
 InstallRootAutorizedKey(){
+	UserRequireRoot "InstallRootAutorizedKey"
+
 	local KEY="$1"
+
+	[ -z "$KEY" ] && echo "InstallRootAutorizedKey: key is required!" && exit 2
+
 	local HOME="/root"
 	local KEYS="$HOME/.ssh/authorized_keys"
 	
@@ -18,9 +23,8 @@ InstallRootAutorizedKey(){
 	chmod 600 "$KEYS"
 }
 
-
-KEY="$1"
-
-[ -z "$KEY" ] && echo "key is required!" && exit 2
-
-InstallRootAutorizedKey "$KEY"
+case "$0" in
+	*/myx.common/bin/lib/installRootAutorizedKey) 
+		InstallRootAutorizedKey $@
+	;;
+esac
