* updated

diff --git a/host/tarball/share/myx.common/bin/lib/installUser b/host/tarball/share/myx.common/bin/lib/installUser
--- a/host/tarball/share/myx.common/bin/lib/installUser
+++ b/host/tarball/share/myx.common/bin/lib/installUser
@@ -3,6 +3,57 @@
 set -e
 #set -x
 
-. ${0%/*}/../../include/subr.sh
+. /usr/local/share/myx.common/include/subr-universal.sh
 
-InstallUser "$1" "$2" "$3" "$4"
+InstallUser(){
+	UserRequireRoot "InstallUser"
+
+	local NAME="$1" TITLE="$2" 
+	local UGID="$3" UHOME="${4:-/home/$NAME/}"
+	
+	[ -z "$NAME" ] && echo "InstallUser: username is required!" && exit 1
+	[ -z "$TITLE" ] && echo "InstallUser: usertitle is taken from name ($NAME)!" && TITLE="$NAME"
+
+	pwd_mkdb /etc/master.passwd
+
+	if ! pw groupshow "$NAME" >/dev/null 2>&1; then \
+		echo "Creating group '$NAME'."
+		pw groupadd -n "$NAME" $(if ! [ -z "$UGID" ] ; then echo "-g $UGID" ; fi)
+		pwd_mkdb /etc/master.passwd
+	 else \
+	 	echo "Using existing group '$NAME'."
+	fi
+
+	mkdir -p "$UHOME"
+	# install -d -g 177 -o 177 "$UHOME"
+
+	if pw usershow "$NAME" > /dev/null 2>&1; then
+		echo "Using existing user '$NAME'."
+		pw usermod "$NAME" -g "$NAME" -c "$TITLE" -d "$UHOME" -s /bin/sh
+	else 
+		echo "Creating user '$NAME'."
+		pw useradd "$NAME" -g "$NAME" $(if ! [ -z "$UGID" ] ; then echo "-u $UGID" ; fi) -c "$TITLE" -d "$UHOME" -s /bin/sh
+	fi
+	
+	pw groupmod "$NAME" -m "$NAME"
+	pwd_mkdb /etc/master.passwd
+	
+	chown $NAME:$NAME "$UHOME/"
+	chmod 700 "$UHOME/"
+
+	mkdir -p "$UHOME/.ssh"
+	chown $NAME:$NAME "$UHOME/.ssh"
+	chmod 700 "$UHOME/.ssh"
+}
+
+
+NAME="$1"
+TITLE="$2"
+
+[ -z "$NAME" ] && echo "username is required!" && exit 1
+[ -z "$TITLE" ] && echo "usertitle is taken from name ($NAME)!" && TITLE="$NAME"
+	
+UGID="$3"
+UHOME="${4:-/home/$NAME/}"
+
+InstallUser "$NAME" "$TITLE" "$UGID" "$UHOME"
