* install/ensure - reorganised

diff --git a/host/tarball/share/myx.common/bin/lib/installEnsurePackage b/host/tarball/share/myx.common/bin/lib/installEnsurePackage
--- a/host/tarball/share/myx.common/bin/lib/installEnsurePackage
+++ b/host/tarball/share/myx.common/bin/lib/installEnsurePackage
@@ -3,31 +3,38 @@
 type UserRequireRoot >/dev/null 2>&1 || \
 	. "/usr/local/share/myx.common/bin/user/requireRoot"
 
+InstallEnsurePackageTransformPackageName(){
+		case "$1" in
+		        java)	
+		        	echo "openjdk13" ; return 0 ;;
+				*)		
+					echo "$1" ; return 0 ;;
+		esac
+}
+
 InstallEnsurePackage(){
 	UserRequireRoot "InstallEnsurePackage"
 
-	local UTILITY_NAME="$1"
-	[ -z "$UTILITY_NAME" ] && echo "The utility name is required!" && exit 1
+	local NAME="$1"
+	[ -z "$NAME" ] && echo "The utility name is required!" && exit 1
 
-	local PACKAGE_NAME="${2:-$UTILITY_NAME}"
-	
-	if [ ! -z "`which $UTILITY_NAME`" ] ; then \
-		echo "Utility is present: $UTILITY_NAME, skip" >&2
-	 else \
-		case "$PACKAGE_NAME" in
-		        java)
-		        	PACKAGE_NAME="openjdk13"
-		        	break
-					;;
-		esac
-	 	pkg install -y $PACKAGE_NAME
-	fi
+	local LIST=""
+
+	for NAME in $@ ; do
+		which -s $NAME \
+			&& echo "ensure: $NAME already present, skip" >&2 \
+			|| LIST="$LIST `InstallEnsurePackageTransformPackageName $NAME`"
+	done
+
+	[ -z "$LIST" ] \
+		&& echo "all packages installed." >&2 \
+		|| pkg install -y $LIST
 }
 
 case "$0" in
 	*/myx.common/bin/lib/installEnsurePackage) 
 		if [ -z "$1" ] ; then
-			echo "Syntax: myx.common lib/installEnsurePackage utility_name [package_name]" >&2
+			echo "Syntax: myx.common lib/installEnsurePackage utility_name [utility_name2 [...]]" >&2
 			exit 1
 		fi
 		set -e
