* minor: mostly if/fi statements

diff --git a/host/tarball/share/myx.common/bin/os/growSlashFsUfs b/host/tarball/share/myx.common/bin/os/growSlashFsUfs
--- a/host/tarball/share/myx.common/bin/os/growSlashFsUfs
+++ b/host/tarball/share/myx.common/bin/os/growSlashFsUfs
@@ -22,34 +22,30 @@ OsGrowSlashFsUfs(){
 
 	if [ "$DISK" = "" ] || [ "$PART" = "" ] ; then
 		local DISKS="$DISK vtbd0 da0"
-		for DSK in $DISKS
-		do
+		for DSK in $DISKS ; do
 			if [ "`geom disk status -s $DSK`" != "" ] ; then
 				local PARTS="${DSK}s1 $DSK"
-				for PRT in $PARTS
-				do
+				for PRT in $PARTS ; do
 					if [ "`gpart status -s $PRT`" != "" ] && [ "`gpart show $PRT | grep freebsd-ufs`" != "" ] ; then
 						OsGrowSlashFsUfs $DSK $PRT
 						return 0;
 					fi
 				done
-				
 			fi
 		done
 		
 		echo "ERROR: Failed: can't detect device and partition (yet)" >&2
 		return 1;
-	else
-		if [ "`geom disk status -s $DISK`" != "" ] ; then
-		else
-			echo "ERROR: Failed: specified disk is invalid: $DISK" >&2
-			return 1;
-		fi
-		if [ "`gpart status -s $PART`" != "" ] && [ "`gpart show $PART | grep freebsd-ufs`" != "" ] ; then
-		else
-			echo "ERROR: Failed: specified part is invalid (or does't contain UFS filesystem): $PART" >&2
-			return 1;
-		fi
+	fi
+
+	if [ "`geom disk status -s $DISK`" = "" ] ; then
+		echo "ERROR: Failed: specified disk is invalid: $DISK" >&2
+		return 1;
+	fi
+
+	if [ "`gpart status -s $PART`" = "" ] || [ "`gpart show $PART | grep freebsd-ufs`" = "" ] ; then
+		echo "ERROR: Failed: specified part is invalid (or does't contain UFS filesystem): $PART" >&2
+		return 1;
 	fi
 	
 	if [ "$INDX" = "" ] ; then
@@ -81,7 +77,7 @@ OsGrowSlashFsUfs(){
 	echo "Current size: ${SIZE_NOW}G" >&2
 
 	if [ "$SWAP" != "" ] ; then
-		swapoff -a
+		swapoff -a || true
 		gpart delete -i $SWAP $PART
 		
 		## TODO: calculate new size and check that it is bigger than current
