+ `--shrink-disk` option for vm/create

diff --git a/host/tarball/share/myx.common/bin/vm/create b/host/tarball/share/myx.common/bin/vm/create
--- a/host/tarball/share/myx.common/bin/vm/create
+++ b/host/tarball/share/myx.common/bin/vm/create
@@ -14,6 +14,13 @@ VmCreate(){
 		return 1
     fi
     
+	local VMHDD="`echo "$VMHDD" | sed 's/[ ]*//g;s/[bB]$//;s/^.*[^0-9gkmt].*$//;s/t$/Xg/;s/g$/Xm/;s/m$/Xk/;s/k$/X/;s/X/*1024/g' | bc`"
+
+	if [ -z "$VMHDD" ] ; then
+		echo "ERROR: Syntax error: vm/create: check arguments: disk size is invalid!" >&2
+		return 1
+	fi
+
     local VMLAN0=""
     local VMMAC0=""
     local VMLAN1=""
@@ -22,6 +29,13 @@ VmCreate(){
     local VMMAC2=""
     local VMLAN3=""
     local VMMAC3=""
+
+	local SHRINK=""
+
+	if [ "$1" == "--shrink-disk" ] ; then
+		shift;
+		SHRINK="true"
+	fi
     
     if [ "$1" == "--net" ] ; then
     	shift;
@@ -190,12 +204,20 @@ VmCreate(){
 		fi
 		
 		if [ ! -z "$VMHDD" ] ; then
-			if [ -f /vms/$VMNAME/disk0.img ] ; then
+			if [ -f "/vms/$VMNAME/disk0.img" ] ; then
 		        echo "Disk type: file image: /vms/$VMNAME/disk0.img" >&2
-				truncate -c -s "$VMHDD" "/vms/$VMNAME/disk0.img"
+				if [ -z "$SHRINK" -a "$VMHDD" -lt "$(sh -c '(eval `stat -s "/vms/$VMNAME/disk0.img"` ; echo $st_size)')" ] ; then
+					echo "WARNING: Shrink is not allowed, use --shrink-disk option!" >&2
+				else
+					truncate -c -s "$VMHDD" "/vms/$VMNAME/disk0.img"
+				fi
 			elif [ ! -z "$( zfs list | grep -e "^zroot/vms/$VMNAME/disk0\s" )" ] ; then
 		        echo "Disk type: zfs volume: zroot/vms/$VMNAME/disk0" >&2
-				zfs set "volsize=$VMHDD" "zroot/vms/$VMNAME/disk0"
+				if [ -z "$SHRINK" -a "$VMHDD" -lt "$(zfs get -H -p -o value volsize zroot/vms/$VMNAME/disk0)" ] ; then
+					echo "WARNING: Shrink is not allowed, use --shrink-disk option!" >&2
+				else
+					zfs set "volsize=$VMHDD" "zroot/vms/$VMNAME/disk0"
+				fi
 			else
 		        echo "Disk type ($VMNAME): not supported / cannot detect" >&2
 		        echo "WARNING: Cannot check/modifiy disk image size, skipped... ($VMNAME)" >&2
@@ -212,7 +234,7 @@ case "$0" in
 	*/myx.common/bin/vm/create) 
 		if [ "$1" = "--help" ] ; then
 			echo "Syntax:" >&2
-			echo "  myx.common vm/create --linux/--freebsd/--ubuntu-lvm <name> <cores> <ram> <disk> [--net <lan-name> <mac-address>...] <iso>" >&2
+			echo "  myx.common vm/create --linux/--freebsd/--ubuntu-lvm <name> <cores> <ram> <disk> [--shrink-disk] [--net <lan-name> <mac-address>...] <iso>" >&2
 			echo "Examples:" >&2
 			echo "	myx.common vm/create --linux      bb1-h1  8  8192M 120G --net lan22 52:54:20:25:20:28 ubuntu-20.04.3-live-server-amd64.iso" >&2
 			echo "	myx.common vm/create --freebsd    dss-h3  8  8192M 120G --net lan22 52:54:20:22:20:32 FreeBSD-13.0-RELEASE-amd64-disc1.iso" >&2
